const positiveMessages = [
  "You are capable of amazing things.",
  "Every day is a new opportunity.",
  "Believe in yourself.",
  "Your smile is contagious.",
  "You make a difference in the world.",
  "You are loved and appreciated.",
  "Dream big and work hard.",
  "Stay positive and keep going.",
  "Life is beautiful; enjoy it.",
  "You are stronger than you think.",
  "Success is within your reach.",
  "You are unique and special.",
  "The best is yet to come.",
  "Chase your dreams with passion.",
  "You are a shining star.",
  "You have a heart of gold.",
  "Positivity is the key to happiness.",
  "Your kindness is a gift to others.",
  "You can overcome any challenge.",
  "Embrace each day with enthusiasm.",
  "Your potential is limitless.",
  "Happiness is a choice; choose it.",
  "You bring joy to those around you.",
  "Stay focused on your goals.",
  "You are enough just as you are.",
  "Make today amazing.",
  "The world is better with you in it.",
  "Keep shining and inspiring.",
  "You have the power to make a difference.",
  "Be the reason someone smiles today.",
  "Your presence is a present to the world.",
  "Stay true to yourself.",
  "You are a source of inspiration.",
  "Every moment is a fresh beginning.",
  "Spread kindness wherever you go.",
  "You are a ray of sunshine.",
  "You are braver than you believe.",
  "The future is bright for you.",
  "You are loved beyond measure.",
  "Your positive attitude is contagious.",
  "Believe in your dreams and make them happen.",
  "You are a masterpiece in progress.",
  "Celebrate your achievements, big and small.",
  "You are a beacon of hope.",
  "Your kindness knows no bounds.",
  "You are a blessing to others.",
  "Keep moving forward with determination.",
  "You are a constant source of joy.",
  "Your potential is limitless.",
  "Stay open to new possibilities.",
  "You are a problem solver.",
  "Believe in the magic within you.",
  "You are a true inspiration.",
  "The best is yet to come for you.",
  "You have a heart full of love.",
  "Stay positive and keep growing.",
  "You are making a positive impact.",
  "You are on the path to success.",
  "Your journey is important and unique.",
  "You are worthy of all good things.",
  "Believe in the power of your dreams.",
  "You light up the world with your smile.",
  "Stay curious and keep learning.",
  "You are a force of nature.",
  "You are a bright star in the sky.",
  "Your optimism is infectious.",
  "Believe in the beauty of your dreams.",
  "You have a heart of gold.",
  "You have the courage to overcome.",
  "Stay true to your values.",
  "You are a beacon of hope.",
  "Every day is a gift; cherish it.",
  "You are making a positive difference.",
  "You are resilient and strong.",
  "Stay true to your unique self.",
  "You are an amazing human being.",
  "Your dreams are worth pursuing.",
  "You are a source of inspiration.",
  "You have the power to change the world.",
  "Stay motivated and keep moving forward.",
  "You are a blessing to others.",
  "Your kindness shines brightly.",
  "You are capable of great things.",
  "You are a true friend and confidant.",
  "Stay positive and watch the world change.",
  "You bring happiness wherever you go.",
  "You are surrounded by love and support.",
  "You are unstoppable.",
  "Believe in your potential and reach for it.",
  "You are a source of strength and courage.",
  "Your heart is full of love and compassion.",
  "Stay focused on your dreams.",
  "You are destined for greatness.",
  "You are a gift to the world.",
  "Keep believing in yourself.",
  "You are a warrior of light.",
  "Your spirit is unbreakable.",
  "You are an inspiration to many.",
  "The world is a better place with you in it.",
  "You have the power to create change.",
  "Stay true to your values and beliefs.",
];
